### ISSUE TITLE
Null is not an object (evaluating 'O.length')

### ISSUE THREAD

**Issue by assellalou** [benawad/vsinder-api#5]
![Screenshot_20201209-235525](https://user-images.githubusercontent.com/19322270/101700534-7e58bd80-3a7d-11eb-9803-9895389c2502.png)

# Reproduction

Once I click the city field the entire app crashes, and shows the error above.

**Comment by benawad** [comment]
should be fixed now

**Comment by assellalou** [comment]
can you please explain how it did happen, and how you managed to fix it. 
Thanks in advance.

**Comment by benawad** [comment]
I am now returning an empty string instead of null for the location https://github.com/benawad/vsinder-api/commit/c762957ece8c65016a5e76a6c906bd9cdb0c1e82
